class ShippingCompany {
  final String name;
  final String code;

  ShippingCompany({required this.name, required this.code});
}

class ShippingCompanies {
  static final List<ShippingCompany> companies = [
    ShippingCompany(name: '3F LIGHT CARGO TRANSPORT CORP', code: '3FLIGHTCARGO'),
    ShippingCompany(name: 'AGRO BULK MARINE CORPORATION', code: 'AGROBULK'),
    ShippingCompany(name: 'ALESON SHIPPING LINES', code: 'ALESON'),
    ShippingCompany(name: 'AL-HILAL INTERNATIONAL SHIPPING CORPORATION', code: 'AL-HILAL'),
    ShippingCompany(name: 'ALJON CARGO SHIPPING INC', code: 'ALJON'),
    ShippingCompany(name: 'ALL ISLAND BARGE CORP', code: 'ALLISLAND'),
    ShippingCompany(name: 'AMPARO SHIPPING CORPORATION', code: 'AMPARO'),
    ShippingCompany(name: 'APO CEMENT CORP', code: 'APO'),
    ShippingCompany(name: 'ARCHIPELAGO CHARTER CARRIERS INC', code: 'ARCHIPELAGO'),
    ShippingCompany(name: 'ASIAN SHIPPING CORP', code: 'ASIAN'),
    ShippingCompany(name: 'ASIANA SEALINES INC', code: 'ASIANA'),
    ShippingCompany(name: 'AVEGA BROS INTEGRATED SHIPPING CORP', code: 'AVEGA'),
    ShippingCompany(name: 'BACOLOD TWINSTAR SHIPPING CORP', code: 'TWINSTAR'),
    ShippingCompany(name: 'BNR CONSTRUCTION AND DEVELOPMENT CORPORATION', code: 'BNR'),
    ShippingCompany(name: 'CANDANO SHIPPING LINES INC', code: 'CANDANO'),
    ShippingCompany(name: 'CELESTIAL COCOPALM CARRIER CORPORATION', code: 'CELESTIAL'),
    ShippingCompany(name: 'CMK STAR SHIPPING CORPORATION', code: 'CMKSTAR'),
    ShippingCompany(name: 'CONCRETE SOLUTIONS INC', code: 'CONCRETE'),
    ShippingCompany(name: 'CSK SHIPPING LINES', code: 'CSK'),
    ShippingCompany(name: 'COKALIONG SHIPPING LINES INC', code: 'COKALIONG'),
    ShippingCompany(name: 'EASTERN ISLAND SHIPPING CORPORATION', code: 'EASTERNISLAND'),
    ShippingCompany(name: 'EASTERNWIND LINE INC', code: 'EASTERNWIND'),
    ShippingCompany(name: 'EFG SHIPPING INC', code: 'EFG'),
    ShippingCompany(name: 'EVA SHIPPING CORPORATION', code: 'EVA'),
    ShippingCompany(name: 'EVARISTO SHIPPING LINES', code: 'EVARISTO'),
    ShippingCompany(name: 'EVERWIN PACIFIC SHIPPING CORP', code: 'EVERWIN'),
    ShippingCompany(name: 'FASTGUYS LOGISTIC CORPORATION', code: 'FASTGUYS'),
    ShippingCompany(name: 'FORTUNE SEA CARRIER INCORPORATED', code: 'FORTUNESEA'),
    ShippingCompany(name: 'FORTUNE STAR SHIPPING', code: 'FORTUNESTAR'),
    ShippingCompany(name: 'GCL SHIPPING LINES', code: 'GCL'),
    ShippingCompany(name: 'GOLDEN ISLANDER MARITIME INC', code: 'GOLDENISLANDER'),
    ShippingCompany(name: 'GOLDEN LINES INC', code: 'GOLDEN'),
    ShippingCompany(name: 'GOLDEN STAR MANING & SHIP MANAGEMENT CORP', code: 'GOLDENSTARMANING'),
    ShippingCompany(name: 'GOLDSTAR SHIPPING LINES INC', code: 'GOLDSTAR'),
    ShippingCompany(name: 'GY SHIPPING', code: 'GY'),
    ShippingCompany(name: 'HAMAKO VENTURES INC', code: 'HAMAKO'),
    ShippingCompany(name: 'HOSANNA SHIPPING CORP', code: 'HOSANNA'),
    ShippingCompany(name: 'INDUSTRY MOVERS CORPORATION', code: 'INDUSTRYMOVERS'),
    ShippingCompany(name: 'INVESTWELL SHIPPING CORPORATION', code: 'INVESTWELL'),
    ShippingCompany(name: 'ISAJ SEA TRANSPORT CORP', code: 'ISAJ'),
    ShippingCompany(name: 'ISLAND SHIPPING CORPORATION', code: 'ISLANDSHIPPING'),
    ShippingCompany(name: 'JEHAN SHIPPING CORP', code: 'JEHAN'),
    ShippingCompany(name: 'JVP LINES INC', code: 'JVP'),
    ShippingCompany(name: 'KEY WEST SHIPPING LINE CORP', code: 'KEYWEST'),
    ShippingCompany(name: 'KHERI LINES INC', code: 'KHERI'),
    ShippingCompany(name: 'KPK SHIPPING LINES', code: 'KPK'),
    ShippingCompany(name: 'LANDING CRAFT TRANSPORT INC', code: 'LANDINGCRAFT'),
    ShippingCompany(name: 'LD SHIPPING LINE', code: 'LD'),
    ShippingCompany(name: 'LEECHAMPS SHIPPING CORPORATION', code: 'LEECHAMPS'),
    ShippingCompany(name: 'LIRIO SHIPPING LINES INC', code: 'LIRIO'),
    ShippingCompany(name: 'LILYGENE SEA TRANSPORT', code: 'LILYGENE'),
    ShippingCompany(name: 'LIOK SHIPPING LINES CORP', code: 'LIOK'),
    ShippingCompany(name: 'MAC18 SHIPPING CO INC', code: 'MAC18'),
    ShippingCompany(name: 'MAGNOLIA SHIPPING CORP', code: 'MAGNOLIA'),
    ShippingCompany(name: 'MANFEL CARGO SHIPPING CORP', code: 'MANFEL'),
    ShippingCompany(name: 'MAYON DIAMOND VESSEL CORPORATION', code: 'MAYON'),
    ShippingCompany(name: 'MATADA SHIPPING LINES', code: 'MATADA'),
    ShippingCompany(name: 'MC PHIL MARU SHIPPING', code: 'MCPHILMARU'),
    ShippingCompany(name: 'MEDALLION TRANSPORT INC', code: 'MEDALLION'),
    ShippingCompany(name: 'MIROLA LOGISTICS CORP', code: 'MIROLA'),
    ShippingCompany(name: 'N & L CARGO SHIPPING CORP', code: 'N&LCARGO'),
    ShippingCompany(name: 'NAVIG8 SHIPPING CORPORATION', code: 'NAVIG8'),
    ShippingCompany(name: 'OCEAN TRANSPORT GROUP OF COMPANIES INC', code: 'OCEANTRANSPORT'),
    ShippingCompany(name: 'OROPHIL SHIPMANAGEMENT CORP', code: 'OROPHIL'),
    ShippingCompany(name: 'PAROS MARITIME INC', code: 'PAROS'),
    ShippingCompany(name: 'PHERWIN SHIPPING CORP', code: 'PHERWIN'),
    ShippingCompany(name: 'PHIL COMMERCIAL TRAMP SHIPPING CORP', code: 'PHILCOM'),
    ShippingCompany(name: 'PKS SHIPPING CO INC', code: 'PKS'),
    ShippingCompany(name: 'PORAQUE VINCENT T', code: 'PORAQUE'),
    ShippingCompany(name: 'PORMIDA PRIMO C/ CSL SHIPPING', code: 'PORMIDA'),
    ShippingCompany(name: 'PREMIUM MEGASTRUCTURES, INC.', code: 'PREMIUM'),
    ShippingCompany(name: 'PRIMARY TRIDENT SOLUTIONS INC', code: 'PRIMARY'),
    ShippingCompany(name: 'RKK SHIPPING LINES CO', code: 'RKK'),
    ShippingCompany(name: 'ROBLE SHIPPING INC', code: 'ROBLE'),
    ShippingCompany(name: 'SAM SOWAH SHIPPING CORP', code: 'SAMSOWAH'),
    ShippingCompany(name: 'SAN NICHOLAS LINES INC', code: 'SANNICHOLAS'),
    ShippingCompany(name: 'SEAFORD SHIPPING LINES INC', code: 'SEAFORD'),
    ShippingCompany(name: 'SEAMINE VENTURES CORP', code: 'SEAMINE'),
    ShippingCompany(name: 'SUN LINES', code: 'SUNLINES'),
    ShippingCompany(name: 'TAC SHIPPING CORP', code: 'TAC'),
    ShippingCompany(name: 'TALISAY SHIPPING LINES INC', code: 'TALISAY'),
    ShippingCompany(name: 'TEKTITE SHIPPING CORP', code: 'TEKTITE'),
    ShippingCompany(name: 'THRESIAN STARS SHIPPING LINES INC', code: 'THERESIAN'),
    ShippingCompany(name: 'UNIFIDE GLOBAL SHIPPING CORP', code: 'UNIFIDE'),
    ShippingCompany(name: 'UNILINK SHIPPING CORP', code: 'UNILINK'),
    ShippingCompany(name: 'VISAYAN INTER-ISLAND SHIPPING', code: 'VISAYANINTERISLAND'),
    ShippingCompany(name: 'WHALE SHIPPING CORP', code: 'WHALE'),
    ShippingCompany(name: 'WIN INDUSTRIAL NETWORK SHIPPING INC', code: 'WIN'),
  ];
}

