// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVNA09E5yHKOpdwUTax_0yv1SfJxvEO4',
    appId: '1:268881505490:web:67983a7869fae4c2af110b',
    messagingSenderId: '268881505490',
    projectId: 'guardianwaves-68df1',
    authDomain: 'guardianwaves-68df1.firebaseapp.com',
    storageBucket: 'guardianwaves-68df1.appspot.com',
    measurementId: 'G-H2W1ZSWCK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbVNA09E5yHKOpdwUTax_0yv1SfJxvEO4',
    appId: '1:268881505490:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '268881505490',
    projectId: 'guardianwaves-68df1',
    storageBucket: 'guardianwaves-68df1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbVNA09E5yHKOpdwUTax_0yv1SfJxvEO4',
    appId: '1:268881505490:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '268881505490',
    projectId: 'guardianwaves-68df1',
    storageBucket: 'guardianwaves-68df1.appspot.com',
    iosBundleId: 'com.guardianwaves.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbVNA09E5yHKOpdwUTax_0yv1SfJxvEO4',
    appId: '1:268881505490:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '268881505490',
    projectId: 'guardianwaves-68df1',
    storageBucket: 'guardianwaves-68df1.appspot.com',
    iosBundleId: 'com.guardianwaves.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbVNA09E5yHKOpdwUTax_0yv1SfJxvEO4',
    appId: '1:268881505490:web:67983a7869fae4c2af110b',
    messagingSenderId: '268881505490',
    projectId: 'guardianwaves-68df1',
    authDomain: 'guardianwaves-68df1.firebaseapp.com',
    storageBucket: 'guardianwaves-68df1.appspot.com',
  );
}
